basic.showIcon(IconNames.EigthNote)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 80)
music.playTone(262, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
music.playTone(262, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 80)
music.playTone(294, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
music.playTone(262, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Yellow)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 80)
music.playTone(220, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(220, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinRight, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
music.playTone(220, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
music.playTone(294, music.beat(BeatFraction.Whole))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
music.playTone(294, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Yellow)
music.playTone(330, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
music.playTone(294, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
music.playTone(262, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
music.playTone(247, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
music.playTone(196, music.beat(BeatFraction.Whole))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinLeft, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Yellow)
music.playTone(330, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
music.playTone(349, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
music.playTone(330, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
music.playTone(294, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinLeft, 80)
music.playTone(262, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
music.playTone(220, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinRight, 80)
music.rest(music.beat(BeatFraction.Whole))
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Yellow)
music.playTone(196, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
music.playTone(220, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
music.playTone(294, music.beat(BeatFraction.Half))
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 80)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Blue)
music.playTone(247, music.beat(BeatFraction.Half))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_SpinLeft, 80)
music.playTone(262, music.beat(BeatFraction.Whole))
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
basic.forever(function () {
	
})
